server {
    listen 80;
    root /usr/share/nginx/html;

    location = / {
        try_files /index.html =404;
    }

    location /de/ {
        rewrite ^/de/(.*)$ /de-CH/$1 last;
    }

    location /fr/ {
        rewrite ^/fr/(.*)$ /fr-CH/$1 last;
    }

    location /de-CH/ {
        try_files $uri $uri/ /de-CH/index.html;
    }

    location /fr-CH/ {
        try_files $uri $uri/ /fr-CH/index.html;
    }
}
