application.hitobito.instance=cevi.puzzle.ch
application.course.groups.include=Cevi Schweiz,Cevi Region Bern,Cevi Alpin,AG-SO-LU-ZG

application.cors.allowed.origin.patterns=https://*.cevi.ch,https://cevi.ch,https://*.cevi.tools,https://cevi.tools,http://localhost:4200

logging.level.ch.cevi.db.adapter = DEBUG
